### ISSUE TITLE
Disabling Cruise Control

### ISSUE THREAD

**Issue by Trooper98** [platisd/smartcar_shield#6]
The method `disableCruiseControl();` method isn't being recognised by the Arduino IDE.

**Comment by platisd** [comment]
I'm abroad at the moment, can you create a pull request that solves this?

**Comment by ArchiCo** [comment]
It seems like the keywords.txt file lacks the proper designation for the disableCruiseControl() method, unlike other method counterparts. My guess is that disableCruiseControl()	KEYWORD2 needs to be added to that file.
