### ISSUE TITLE
support servo drivemotor?

### ISSUE THREAD

**Issue by samuk** [platisd/smartcar_shield#60]
## Description
Does this lib support servos as drive motors? 
## Definition of Done

This chassis works using just esp32 and 5v power source

https://m.aliexpress.com/item/32607362464.html

**Comment by platisd** [comment]
At first I thought you meant an ESC ([which is supported](https://platisd.github.io/smartcar_shield/class_servo_motor.html)) but I now see that you mean those continuous rotation "servo" motors.

Can you remind me how do you set the speed for them? It shouldn't be hard to implement something if not already supported.

**Comment by samuk** [comment]
it's just PWM https://dronebotworkshop.com/esp32-servo/

I think you already have the esp32servo lib installed?

**Comment by platisd** [comment]
The particular sensors are a little special in the sense that you cannot set a "speed" on them. They just move at a set speed forward or backward. But anyway, if you replace `BrushedMotor` with `ServoMotor` in [SimpleCar.ino](https://github.com/platisd/smartcar_shield/blob/master/examples/Car/SimpleCar/SimpleCar.ino) it should work.

**Comment by samuk** [comment]
Great I'll give it a go, thanks
