### ISSUE TITLE
supported IMU/ motor driver  list

### ISSUE THREAD

**Issue by samuk** [platisd/smartcar_shield#61]
## Description

Is there a list of supported IMU anywhere? Or is it just the GY50?

I'd be particularly interested in any of the breakout garden IMU? 
https://shop.pimoroni.com/collections/breakout-garden?q=robot 

## Definition of Done
Documentation includes list of supported hardware,  or clarifies rhat it is only GY50 that is supported

**Comment by platisd** [comment]
Currently only the GY-50 is supported as mentioned in [Supported sensors](https://github.com/platisd/smartcar_shield#supported-sensors)

**Comment by samuk** [comment]
Thanks. I might see if I can add support for https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/arduino-code
