### ISSUE TITLE
Motor driver abstraction

### ISSUE THREAD

**Issue by samuk** [platisd/smartcar_shield#67]
## Description

This lib seems to do a nice job of abstracting motor drivers: https://github.com/tfeldmann/Arduino-MotorDriver

Could you provide some example code for how you would integrate that with your library?

## Definition of Done

It's clear how to use various types of motor driver with the Smartcar_shield library.

**Comment by platisd** [comment]
This library already does the same thing too (among others). Why would you like to integrate it?
